### ISSUE TITLE
Expanded | Collapse

### ISSUE THREAD

**Issue by RasheshAccenture** [NuPlay/ExpandableText#2]
Once expanded, How can I collapse?
e.g. I want to collapse on tap on label like toggle. Tap to expand and again tap to collapse.

Even I want different font and colour for `read more` button.

**Comment by NuPlay** [comment]
sorry for the late reply

And I'm going to add a button.
Do you want the text, expand button, and collapse button to have different fonts and colors?

**Comment by NuPlay** [comment]
I added that function. #4
