### ISSUE TITLE
Text is being repeated when view is in the collapsed state with the "more"

### ISSUE THREAD

**Issue by shahsarth** [NuPlay/ExpandableText#9]
To reproduce this error you will need to enter a very long piece of text. For me I used:

How to win Friends and Influence People:
I gave myself the challenge in the year of 2022 to read more. My goal is to read 1 book a month, so 12 books by the end of the year. I just finished this classic book. This has been overdue on my reading list for a while, and I’m so glad I read it. There are so many
valuable lessons that help with how you communicate with people. Some of my favorites include: 
1) Be heavy on your praise and avoid criticizing.
2) Talk about what people enjoy and are interested in, instead of talking about what I’m interested in all the time.
3) Avoid an argument in the first place. Nothing productive is done once people are in the mindset of an argument.
4) Be genuine with compliments. Really think what’s something about them that you really admire and then let them know.
5) Put yourself in their shoes, appreciate and understand the world the way others see it. At the end of the day we are a product of our environments, and given a different situation or circumstance you might hold the same views as the person you think is wrong.
P.S. - This book is definitely one that really needs to be read multiple times to internalize the messages. In addition, these mindset changes need to be actively practiced to properly develop. I will definitely need to work on this still.

^Try this text out with the Expandable Text and it will cause the bug of repeating text.

**Comment by NuPlay** [comment]
I've tested it many times but I can't reproduce the issue 😢
